C Read in nfseg simulated heads 
C Extract and evaluated area weighted average UFA heads beneath lakes
C Export extracted heads for SP1 and SP2

	PROGRAM MAIN

	PARAMETER(NROW=752,NCOL=704,NLAY=7,NSP=2)
	CHARACTER TEXT1*16,LINE*100
	INTEGER IT1,IT2,NC,NR,NL	
      DIMENSION XVS(NCOL,NROW,NLAY,NSP)

	PARAMETER(NLAKES1=84,NLAKECELLS1=997)
	PARAMETER(NLAKES2=259,NLAKECELLS2=2645)
	PARAMETER(NLAKES3=3,NLAKECELLS3=33)
	DIMENSION HDSLKS1(NLAKES1,NSP),HDSLKS2(NLAKES2,NSP),
     &	HDSLKS3(NLAKES3,NSP)

C	READ SIMULATED HEADS	
	OPEN(21,FILE='nfseg.hds',FORM='BINARY',STATUS='OLD')
	DO ISP=1,NSP
	 DO ILAY=1,NLAY
	 READ(21) IT1,IT2,PERTIM,TOTIM,TEXT1,NC,NR,NL
	 print*, IT1,IT2,PERTIM,TOTIM,TEXT1,NC,NR,NL
	 READ(21) XVS(:,:,NL,ISP)
	 ENDDO
	ENDDO
	CLOSE(21)

C	EXTRACT AND EVALUATE AREA-AVERAGED LAKE UFA HEADS
	OPEN(22,FILE='WaterBodiesFromVito.dat',STATUS='OLD')
	READ(22,*)
	DO ICELL = 1,NLAKECELLS1
	READ(22,*)ID,IROW,ICOL,RATIO
	HDSLKS1(ID,1)=HDSLKS1(ID,1)+XVS(ICOL,IROW,3,1)*RATIO
	HDSLKS1(ID,2)=HDSLKS1(ID,2)+XVS(ICOL,IROW,3,2)*RATIO
	WRITE(*,*)ID,IROW,ICOL,RATIO,HDSLKS1(ID,1),HDSLKS1(ID,2)
	END DO
	CLOSE(22)

	OPEN(32,FILE='WaterBodiesFromVito.ufahds',STATUS='UNKNOWN')
	WRITE(32,*)"LakeID UFA_Head_SP1 UFA_Head_SP2"
	DO ILAKE = 1,NLAKES1
	WRITE(32,*)ILAKE,HDSLKS1(ILAKE,1),HDSLKS1(ILAKE,2)
	ENDDO
	CLOSE(32)

	OPEN(23,FILE='WaterBodiesFromTrey.dat',STATUS='OLD')
	READ(23,*)
	DO ICELL = 1,NLAKECELLS2
	READ(23,*)ID,IROW,ICOL,RATIO
	HDSLKS2(ID,1)=HDSLKS2(ID,1)+XVS(ICOL,IROW,3,1)*RATIO
	HDSLKS2(ID,2)=HDSLKS2(ID,2)+XVS(ICOL,IROW,3,2)*RATIO
	WRITE(*,*)ID,IROW,ICOL,RATIO,HDSLKS2(ID,1),HDSLKS2(ID,2)
	END DO
	CLOSE(23)

	OPEN(33,FILE='WaterBodiesFromTrey.ufahds',STATUS='UNKNOWN')
	WRITE(33,*)"LakeID UFA_Head_SP1 UFA_Head_SP2"
	DO ILAKE = 1,NLAKES2
	WRITE(33,*)ILAKE,HDSLKS2(ILAKE,1),HDSLKS2(ILAKE,2)
	ENDDO
	CLOSE(33)

	
	OPEN(24,FILE='WaterBodiesFromJohnGood.dat',STATUS='OLD')
	READ(24,*)
	DO ICELL = 1,NLAKECELLS3
	READ(24,*)ID,IROW,ICOL,RATIO
	HDSLKS3(ID,1)=HDSLKS3(ID,1)+XVS(ICOL,IROW,3,1)*RATIO
	HDSLKS3(ID,2)=HDSLKS3(ID,2)+XVS(ICOL,IROW,3,2)*RATIO
	WRITE(*,*)ID,IROW,ICOL,RATIO,HDSLKS3(ID,1),HDSLKS3(ID,2)
	END DO
	CLOSE(24)

	OPEN(34,FILE='WaterBodiesFromJohnGood.ufahds',STATUS='UNKNOWN')
	WRITE(34,*)"Lake# UFA_Head_SP1 UFA_Head_SP2"
	DO ILAKE = 1,NLAKES3
	WRITE(34,*)ILAKE,HDSLKS3(ILAKE,1),HDSLKS3(ILAKE,2)
	ENDDO
	CLOSE(34)

	STOP
	END
